language: python
python: ['3.6', 3.6-dev]
install:
- python setup.py sdist bdist_wheel
- pip install -r requirements.txt
- python -m pip install dist/nostalgiaforever-*.tar.gz --ignore-installed --no-deps
script:
- >
  ipython --config nostalgiaforever/ipyconfig.py -m pytest
    nostalgiaforever/informal.ipynb
    nostalgiaforever/formal.ipynb
    nostalgiaforever/continuous.ipynb
- ipython --config nostalgiaforever/ipyconfig.py -m unittest tests
- ipython profile create
- importnb-install
- ipython -m readme
