language: python
python:
- '3.6'
- 3.6-dev
install:
- python setup.py sdist bdist_wheel
- pip install -r requirements.txt
- python -m pip install dist/nostalgiaforever-*.tar.gz --ignore-installed --no-deps
script:
- tox
- ipython profile create
- importnb-install
- ipython -m readme
deploy:
- provider: pypi
  user: docfast
  skip-cleanup: true
  password:
    secure: TEPhr4TAWsWaZsi/W5Tdtv+oThEsgOeAHBeFEFSQJNrd3SKdFefX/a++jlCusqftUHwH5udvJ7AwcJsyvng8mIRZZ60AXOyuavG28DqfpxwvGx7FR4cOtsxuBs9HKtmnHqjk1huLDPheRrKOGnwVWZ+IQosc6E31N+IxZQAhKmkR8I9mi1PF5g2I3KU9pFG0Z2IF8tziSw3XYQrciOR60VuWceaQiGATyydualw+G7RYtEeSJ2AMuPVszVFT9g/P0JogtsdLxg7i+2Yt5ybeUr5x8vsbWVIYYLxOge9QrEOis014GwyjF14D7DHD/G/uINhvdGXdbs2mSpDj45bSPlkysl0gNIPol3eKN4bZW4vDw9ZGDKib9Z9r1eWxF6J8lNSmijENwNLhPI4x24qCBGM93R/bYhIONuIxACGM3FHNwWz6mekTcu1gTYI6g58Xsqkuab1oZgh69q793XPzih8lFW1H4WAD141UyITi1KIuS13MmTD35j05ED+mDSioe53MjXHkd9ajjASlt+Jd+IsGTyTj0PRpkRTG4d88wzfFJ7KZ4ZEzXIOPK6Rmv5Mx+3wjx7c7BdsJbIk4hHcFY1UFmdq+45fOcmMSa8Yg0DRYO5eI9vuHVkKVx26zK7zq764YhJXiTbMSRwoIaWd8rlK5soxHn24JyCYeIQieA0o=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: deathbeds/nostalgiaforever
    python: '3.6'
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: $TRAVIS_BRANCH
    python: '3.6'
