language: python
python: ['3.6', 3.6-dev]
install:
- python setup.py sdist bdist_wheel
- pip install -r requirements.txt
- python -m pip install dist/nostalgiaforever-*.tar.gz --ignore-installed --no-deps
script:
- ipython profile create
- cp nostalgiaforever/ipyconfig.py /home/travis/.ipython/profile_default/ipython_config.py
- ipython -m pytest nostalgiaforever/formal.ipynb
- ipython -m unittest tests
- importnb-install
- ipython -m readme

deploy: []
